version: "3.8"

services:
  php:
    container_name: watch_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./watch:/var/www/watch

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./watch:/var/www/watch
      - ./tower/dst:/var/www/tower
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
